[package]
name = "anmixiu-render-d3d11"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anmixiu-scene.workspace = true
thiserror.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = [
    "Foundation_Numerics",
    "Win32_Foundation",
    "Win32_Graphics_Direct2D",
    "Win32_Graphics_Direct2D_Common",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
] }
windows-numerics.workspace = true

[target.'cfg(target_os = "windows")'.dev-dependencies]
anmixiu-text-directwrite.workspace = true
windows = { workspace = true, features = ["Win32_UI_WindowsAndMessaging"] }

[lints]
workspace = true
