[package]
name = "anmixiu"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = []
devtools = [
    "anmixiu-core/devtools",
    "anmixiu-platform-macos/devtools",
    "anmixiu-platform-windows/devtools",
]
tailwind = ["anmixiu-core/tailwind"]
macros = ["dep:anmixiu-macros"]

[dependencies]
anmixiu-core.workspace = true
anmixiu-reactive.workspace = true
anmixiu-macros = { workspace = true, optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
anmixiu-platform-macos.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
anmixiu-platform-windows.workspace = true

[dev-dependencies]
tokio.workspace = true
tracing-subscriber.workspace = true

[[example]]
name = "counter"
path = "../../examples/counter.rs"
required-features = ["tailwind"]

[[example]]
name = "scroll"
path = "../../examples/scroll.rs"
required-features = ["tailwind"]

[[example]]
name = "event"
path = "../../examples/event.rs"
required-features = ["tailwind"]

[[example]]
name = "multi_window"
path = "../../examples/multi_window.rs"
required-features = ["tailwind"]

[[example]]
name = "backdrop_blur"
path = "../../examples/backdrop_blur.rs"
required-features = ["tailwind"]

[lints]
workspace = true
